In [2]:
#1. # Create a constant array
import numpy as np
arr=np.full((2,2),7.)
arr

array([[7., 7.],
       [7., 7.]])

In [ ]:
#Create an array filled with random values
rng=np.random.default_rng()

array_1d = rng.random(4)
print("1D Float Array:\n", array_1d)

array_2d = rng.random((2, 2))
print("\n2D Float Array:\n", array_2d)

1D Float Array:
 [0.30934178 0.52741818 0.52040927 0.83552558]

2D Float Array:
 [[0.14635604 0.63468421]
 [0.65793968 0.38663482]]


#3. Create a NumPy array containing the numbers from 10 to 50. Display:

The array
Number of elements
Shape
Dimension
Data type

In [5]:
arr=np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
len(arr)

41

In [7]:
arr.shape

(41,)

In [8]:
arr.dtype

dtype('int64')

4. Using NumPy, create:

A 1D array containing 10 zeros
A 3 × 3 array containing ones
A 4 × 4 identity matrix
An array containing numbers from 5 to 50 with a step size of 5.

In [9]:
ar0=np.zeros(10)
ar0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
arr0=ar0.astype('i')
print(arr0)

[0 0 0 0 0 0 0 0 0 0]


In [18]:
arr1=np.ones((3,3)).astype('i')
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
ar=np.arange(5,50,5)
ar

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

5. Create an array containing numbers from 1 to 24. Reshape it into:

4 × 6
6 × 4
2 × 3 × 4

Display the shape and ndim of each result.

In [25]:
arr124=np.arange(1,25)
arr124

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [35]:
ar46=arr124.reshape(4,6)
print(ar46)
print("shape:",ar46.shape)
print("ndim:",ar46.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
shape: (4, 6)
ndim: 2


In [36]:
ar64=arr124.reshape(6,4)
print(ar64)
print("shape:",ar64.shape)
print("ndim:",ar64.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
shape: (6, 4)
ndim: 2


In [37]:
ar234=arr124.reshape(2,3,4)
print(ar234)
print("shape:",ar234.shape)
print("ndim:",ar234.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape: (2, 3, 4)
ndim: 3


6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

Write NumPy statements to display:

First element
Last element
Third element
First four elements
Last three elements

In [39]:
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
print(marks[0])
print(marks[-1])
print(marks[2])
print(marks[:4])
print(marks[-3:])

78
81
92
[78 85 92 67]
[73 95 81]


7. Create:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

Calculate:

a + b
a - b
a * b
a / b
Square of every element in a

In [43]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]


8. Given:
salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])

Find:

Total salary
Average salary
Highest salary
Lowest salary
Median salary
Standard deviation

In [46]:
salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])
print("Total salary: ",salary.sum())
print("Average salary: ",salary.sum()/len(salary))
print("Highest salary: ",salary.max())
print("Lowest salary: ",salary.min())
print("Median salary ",np.median(salary))
print("Standard deviation",salary.std())

Total salary:  290000
Average salary:  36250.0
Highest salary:  50000
Lowest salary:  25000
Median salary  35000.0
Standard deviation 8317.902379807063


9. Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

Using NumPy boolean indexing, find:

Marks greater than 75
Marks between 50 and 80
Number of students who scored below 50
Percentage of students who scored 60 or above

Do not use a Python for loop.

In [58]:
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
print("Marks greater than 75 :",marks[marks>75])
print("Marks between 50 and 80 :",marks[(marks>50) & (marks>80)])
print("Number of students who scored below 50 :",marks[marks<50])
print("Marks greater than 60 :",marks[marks>=60])
print("Percentage of students who scored 60 or above:", len(marks[marks>=60])/len(marks)*100)

Marks greater than 75 : [78 89 90 76 84]
Marks between 50 and 80 : [89 90 84]
Number of students who scored below 50 : [45 32 41]
Marks greater than 60 : [78 89 67 90 76 84]
Percentage of students who scored 60 or above: 60.0
